final Map<String, String> schools = {
  'Астана ФМН': 'https://ast.nis.edu.kz',
  'Кокшетау ФМН': 'https://kt.nis.edu.kz',
  'Талдыкорган ФМН': 'https://tk.nis.edu.kz',
  'Семей ФМН': 'https://sm.nis.edu.kz',
  'Орал ФМН': 'https://ura.nis.edu.kz',
  'Усть-Каменогорск ХБН': 'https://ukk.nis.edu.kz', 
  'Актобе ФМН': 'https://akb.nis.edu.kz',
  'Караганда ХБН': 'https://krg.nis.edu.kz',
  'Шымкент ХБН': 'https://hbsh.nis.edu.kz',
  'Шымкент ФМН': 'https://fmsh.nis.edu.kz',
  'Тараз ФМН': 'https://trz.nis.edu.kz',
  'Кызылорда ХБН': 'https://kzl.nis.edu.kz',
  'Павлодар ХБН': 'https://pvl.nis.edu.kz',
  'Атырау ХБН': 'https://atr.nis.edu.kz',
  'Алматы ФМН': 'https://fmalm.nis.edu.kz',
  'Костанай ФМН': 'https://kst.nis.edu.kz',
  'Петропавловск ХБН': 'https://ptr.nis.edu.kz',
  'Алматы ХБН': 'https://hbalm.nis.edu.kz',
  'Актау ХБН': 'https://akt.nis.edu.kz',
};