final Map<String, String> schools = {
  'Астана ФМН': 'https://sms.ast.nis.edu.kz',
  'Кокшетау ФМН': 'https://sms.kt.nis.edu.kz',
  'Талдыкорган ФМН': 'https://sms.tk.nis.edu.kz',
  'Семей ФМН': 'https://sms.sm.nis.edu.kz',
  'Орал ФМН': 'https://sms.ura.nis.edu.kz',
  'Усть-Каменогорск ХБН': 'https://sms.ukk.nis.edu.kz', 
  'Актобе ФМН': 'https://sms.akb.nis.edu.kz',
  'Караганда ХБН': 'https://sms.krg.nis.edu.kz',
  'Шымкент ХБН': 'https://sms.hbsh.nis.edu.kz',
  'Шымкент ФМН': 'https://sms.fmsh.nis.edu.kz',
  'Тараз ФМН': 'https://sms.trz.nis.edu.kz',
  'Кызылорда ХБН': 'https://sms.kzl.nis.edu.kz',
  'Павлодар ХБН': 'https://sms.pvl.nis.edu.kz',
  'Атырау ХБН': 'https://sms.atr.nis.edu.kz',
  'Алматы ФМН': 'https://sms.fmalm.nis.edu.kz',
  'Костанай ФМН': 'https://sms.kst.nis.edu.kz',
  'Петропавловск ХБН': 'https://sms.ptr.nis.edu.kz',
  'Алматы ХБН': 'https://sms.hbalm.nis.edu.kz',
  'Актау ХБН': 'https://sms.akt.nis.edu.kz',
};